// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { ReactNode } from 'react';
import Navbar from '../components/Navbar';
import AboutSection from '../components/AboutSection';
import "./globals.css";
import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function Layout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
{/*                 <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css" /> */}
{/*                 <link rel="stylesheet" href="/assets/css/animate.css" /> */}
{/*                 <link rel="stylesheet" href="/assets/css/responsive.css" /> */}
{/*                 <link rel="stylesheet" href="/assets/css/slicknav.css" /> */}
{/*                 <link rel="stylesheet" href="/assets/css/nivo-lightbox.css" /> */}
            </head>
            <body>
                <header id="header-wrap">
                    <Navbar/>
                </header>
                <AboutSection/>
                {children}
                <Script src="/assets/js/jquery-min.js" strategy="beforeInteractive" />
                <Script src="/assets/js/bootstrap.min.js" strategy="beforeInteractive" />
                <Script src="/assets/js/jquery.nav.js" strategy="beforeInteractive" />
            </body>
        </html>
    );
}
